config/routes.rb
Dnut::Application.routes.draw do

  get "flatuipro_demo/index"
  resources :articles

  resources :articletypes

  resources :stadards

  resources :albums

  resources :photos

  devise_for :users
  resources :varieties

  root 'welcome#index'

  

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/articletype.rb
class Articletype < ActiveRecord::Base
end

app/models/index.rb
class Index < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base

end

app/models/stadard.rb
class Stadard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/variety.rb
class Variety < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :type)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :rating, :user_id)
    end
end

app/controllers/varieties_controller.rb
class VarietiesController < ApplicationController
  before_action :set_variety, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /varieties
  # GET /varieties.json
  def index
    @varieties = Variety.all
  end

  # GET /varieties/1
  # GET /varieties/1.json
  def show
  end

  # GET /varieties/new
  def new
    @variety = Variety.new
  end

  # GET /varieties/1/edit
  def edit
  end

  # POST /varieties
  # POST /varieties.json
  def create
    @variety = Variety.new(variety_params)

    respond_to do |format|
      if @variety.save
        format.html { redirect_to @variety, notice: 'Variety was successfully created.' }
        format.json { render action: 'show', status: :created, location: @variety }
      else
        format.html { render action: 'new' }
        format.json { render json: @variety.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /varieties/1
  # PATCH/PUT /varieties/1.json
  def update
    respond_to do |format|
      if @variety.update(variety_params)
        format.html { redirect_to @variety, notice: 'Variety was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @variety.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /varieties/1
  # DELETE /varieties/1.json
  def destroy
    @variety.destroy
    respond_to do |format|
      format.html { redirect_to varieties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variety
      @variety = Variety.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variety_params
      params.require(:variety).permit(:name, :bush_info, :bush_height, :crown_shape, :growth_rate, :shoots, :hazelnut_info, :haze)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/articletypes_helper.rb
module ArticletypesHelper
end

app/helpers/i_ndices_helper.rb
module INdicesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/stadards_helper.rb
module StadardsHelper
end

app/helpers/varieties_helper.rb
module VarietiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/varieties/_form.html.erb
<%= simple_form_for(@variety) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :bush_info %>
    <%= f.input :bush_height %>
    <%= f.input :crown_shape %>
    <%= f.input :growth_rate %>
    <%= f.input :shoots %>
    <%= f.input :hazelnut_info %>
    <%= f.input :hazelnut_weight %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/varieties/edit.html.erb
<h1>Editing variety</h1>

<%= render 'form' %>

<%= link_to 'Show', @variety %> |
<%= link_to 'Back', varieties_path %>

app/views/varieties/index.html.erb
<h1>Listing varieties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bush info</th>
      <th>Bush height</th>
      <th>Crown shape</th>
      <th>Growth rate</th>
      <th>Shoots</th>
      <th>Hazelnut info</th>
      <th>Haze</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @varieties.each do |variety| %>
      <tr>
        <td><%= variety.name %></td>
        <td><%= variety.bush_info %></td>
        <td><%= variety.bush_height %></td>
        <td><%= variety.crown_shape %></td>
        <td><%= variety.growth_rate %></td>
        <td><%= variety.shoots %></td>
        <td><%= variety.hazelnut_info %></td>
        <td><%= variety.haze %></td>
        <td><%= link_to 'Show', variety %></td>
        <td><%= link_to 'Edit', edit_variety_path(variety) %></td>
        <td><%= link_to 'Destroy', variety, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variety', new_variety_path %>

app/views/varieties/new.html.erb
<h1>New variety</h1>

<%= render 'form' %>

<%= link_to 'Back', varieties_path %>

app/views/varieties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @variety.name %>
</p>

<p>
  <strong>Bush info:</strong>
  <%= @variety.bush_info %>
</p>

<p>
  <strong>Bush height:</strong>
  <%= @variety.bush_height %>
</p>

<p>
  <strong>Crown shape:</strong>
  <%= @variety.crown_shape %>
</p>

<p>
  <strong>Growth rate:</strong>
  <%= @variety.growth_rate %>
</p>

<p>
  <strong>Shoots:</strong>
  <%= @variety.shoots %>
</p>

<p>
  <strong>Hazelnut info:</strong>
  <%= @variety.hazelnut_info %>
</p>

<p>
  <strong>Haze:</strong>
  <%= @variety.haze %>
</p>

<%= link_to 'Edit', edit_variety_path(@variety) %> |
<%= link_to 'Back', varieties_path %>