config/routes.rb
Dnut::Application.routes.draw do

  get "flatuipro_demo/index"
  resources :articles

  resources :articletypes

  resources :stadards

  resources :albums

  resources :photos

  devise_for :users
  resources :varieties

  root 'welcome#index'

  

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/articletype.rb
class Articletype < ActiveRecord::Base
end

app/models/index.rb
class Index < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base

end

app/models/stadard.rb
class Stadard < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/variety.rb
class Variety < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :type)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/articletypes_helper.rb
module ArticletypesHelper
end

app/helpers/i_ndices_helper.rb
module INdicesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/stadards_helper.rb
module StadardsHelper
end

app/helpers/varieties_helper.rb
module VarietiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Hazelnuts! - Welcome to nuts world!

    = stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    = stylesheet_link_tag "bootstrap/css/bootstrap.css"
    = stylesheet_link_tag "bootstrap/css/bootstrap-responsive.css"
    = stylesheet_link_tag "css/flat-ui.css"

body

  /
  /script src="js/jquery-1.8.3.min.js"
  /script src="js/jquery-ui-1.10.3.custom.min.js"
  /script src="js/jquery.ui.touch-punch.min.js"
  /script src="js/bootstrap.min.js"
  /script src="js/bootstrap-select.js"
  /script src="js/bootstrap-switch.js"
  /script src="js/flatui-checkbox.js"
  /script src="js/flatui-radio.js"
  /script src="js/jquery.tagsinput.js"
  /script src="js/jquery.placeholder.js"
  /script src="js/jquery.stacktable.js"

  javascript:
    (function(i,s,o,g,r,a,m) {
      i['GoogleAnalyticsObject']=r;
      i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)
      },i[r].l=1*new Date();
      a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];
      a.async=1;a.src=g;
      m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46702405-1', 'hazelnuts.herokuapp.com');
    ga('send', 'pageview');


  .navbar.navbar-inverse
    .navbar-inner
      .container
        button.btn.btn-navbar data-target="#nav-collapse-03" data-toggle="collapse" type="button"
        = link_to "Hazelnuts!", root_path, :class => 'brand'
        #nav-collapse-03.nav-collapse.collapse
          ul.nav
            li.active
              = link_to "Varieties", varieties_path
            li
              = link_to "Photo"
              ul
                li= link_to "Photo", photos_path
                li= link_to "Albums", albums_path
            li
              = link_to "Article"
              ul
                li= link_to "Articles", articles_path
                li = link_to "Articletypes", articletypes_path
              /! /Sub menu

          /form.navbar-search.form-search.pull-left action="" align="center"
          /  .input-append
          /    input.search-query.span2 placeholder="Search" type="text"
          /      button.btn.btn-large type="submit"
          /        i.fui-search

          - if signed_in?
            ul.nav.pull-right
              li.divider
              li.dropdown
                a.dropdown-toggle data-toggle="dropdown" href="#"
                  signin
                    = current_user.email
                  b.caret
                ul.dropdown-menu
                  li= link_to "Profile", root_path
                  li= link_to "Action", root_path
                  li.divider
                  li = link_to 'Log Out', destroy_user_session_path, :method => :delete
          - else
            ul.nav.pull-right
              li.divider
              li = link_to 'Log In', new_user_session_path

  .row
    - if notice
      p.notice= notice
    - if alert
      p.alert= alert
    .content
      = yield

  br
  br
  footer
    .navbar
      .navbar-inner
        = link_to "Hazelnuts!", root_path, :class => 'brand'
        ul.nav
          li= link_to "Main", root_path